categories: 类别
search: 搜索
tags: Tags
tagcloud: 标签
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
rss_feed: RSS
rss: RSS
category: Category
tag: Tag
social: Social
friend_links: 关于
read_more: 回复
home: Home
archives: 记录
about: About
search_local: 搜索
search_google: googleSearch
search_placeholder: 你要搜索什么？
author: Author
date: Published Date
update: Updated Date
post_categories: Categories
post_tags: Tags
post_licence: 许可
notification: 通知
toc: 目录
visit_counter_uv: 访客
visit_counter_pv: 共计
